# Generated by Django 4.2.24 on 2025-11-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='category_id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
