# Generated by Django 4.2.24 on 2025-11-16 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transactioncategory_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
