# Generated by Django 4.2.24 on 2025-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategory',
            name='category_color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='transactioncategory',
            unique_together={('user_id', 'category_name')},
        ),
    ]
